#Coding a Neuron from scratch


## manual implementation of neuron output calculation


In [ ]:
#Coding a 4 neuron layer, with 4 inputs associated with each neuron

inputs = [3,4,5,6]

weights = [[1,2,3,4],[2,2,3,4],[5,3,2,3]]
b1=3
b2=4
b3=5

#unpacking into individual weight lists
weight1 = weights[0]
weight2 = weights[1]
weight3 = weights[2]

output = [
    weight1[0]*inputs[0]+
    weight1[1]*inputs[1]+
    weight1[2]*inputs[2]+
    b1,

    weight2[0]*inputs[0]+
    weight2[1]*inputs[1]+
    weight2[2]*inputs[2]+
    b2,

    weight3[0]*inputs[0]+
    weight3[1]*inputs[1]+
    weight3[2]*inputs[2]+
    b3,
]
output



[29, 33, 42]

##using loops

In [ ]:
#Now this is tedious to do by hand for more neurons or layers, so we'll loop it over

inputs = [3,4,5,6]
weights = [[1,2,3,4],[2,2,3,4],[5,3,2,3]]
biases= [3,4,5]

layer_outputs = []

for neuron_weights, bias in zip(weights, biases):
  neuron_output = 0
  for weight, input in zip(neuron_weights, inputs):
    neuron_output+=weight*input
  neuron_output+=bias
  layer_outputs.append(neuron_output)

print(layer_outputs)

[53, 57, 60]


##Using Numpy

In [ ]:
import numpy as np
# Single neuron
wights = [1,2,3,4]
inputs = [1,2,3,4]
bias = 1
output = np.dot(weights, inputs)+bias
output

array([31, 32, 30])

In [ ]:
# layer of 3 neurons lets say
weights = [[1,2,3,2],[3,2,3,1],[5,4,3,2]]
inputs = [1,2,3,4]
biases = [1,2,3]

output2 = np.dot(wights, inputs)+biases
output2


array([31, 32, 33])

In [ ]:
# batch of inputs
ip = [[1,2,3],[1,2,3],[1,3,3]]
wei = [[4,4,4],[1,1,1],[3,3,3]]
bia = [1,2,3]

#now for each batch of inputs, we have 3 outputs(as we have three neurons), so we will end up with a total of 9 outputs for 3 batches
output3 = np.dot(ip,np.array(wei).T)+bia #can't transpose a python list, convert to a numpy array, then transposed
output3


array([[25,  8, 21],
       [25,  8, 21],
       [29,  9, 24]])

In [ ]:
#here, the rows are outputs of each neuron for 1 batch of data