#Coding neuron layers

In [5]:
import numpy as np
# a network with an input layer, a hidden layer(3 neurons), and a final layer(3 neurons)

inputs = [[1,2,3,4],[1,3,3,5],[1,3,4,5]]

w1 = [[1,1,1,2],[2,2,2,2],[3,3,3,4]]
b1 =[1,2,3]

w2 = [[1,2,3],[1,3,4],[4,3,2]]
b2=[2,3,4]

# converting all these to numpy arrays for robustness
inputs_array = np.array(inputs)
w1_array = np.array(w1)
b1_array = np.array(b1)
w2_array = np.array(w2)
b2_array = np.array(b2)

layer1_outputs = np.dot(inputs_array, w1_array.T)+b1_array
layer2_outputs = np.dot(layer1_outputs, w2_array.T)+b2_array
print(layer2_outputs)

[[172 232 204]
 [204 275 242]
 [218 294 258]]


In [ ]:
#remember, the rows are batchwise outputs for each neuron, columns are neuron 1, neuron 2 and so on