In [21]:
import numpy as np

In [22]:
inputs = [0.2,5,-10,2.4,-3.2]
outputs = np.maximum(0,inputs)
outputs

array([0.2, 5. , 0. , 2.4, 0. ])

In [23]:
class DenseLayer:
  def __init__(self,n_inputs,n_neurons):
    self.weights = 0.01*np.random.randn(n_inputs,n_neurons)
    self.biases = np.zeros((1,n_neurons))
  def forward(self,inputs):
    self.inputs = inputs
    self.output = np.dot(self.inputs,self.weights)+self.biases
class Relu:

  def forward(self,inputs):
    self.output = np.maximum(0,inputs)
class softmax:
  def forward(self,inputs):
    exp_values = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
    probabilities = exp_values/np.sum(exp_values,axis=1,keepdims = True)
    self.output = probabilities

In [24]:
from nnfs.datasets import spiral_data
import nnfs
nnfs.init()

In [30]:
X,y = spiral_data(samples=100,classes=3)

#Create layers, and activation functions
layer1 = DenseLayer(2,3)
activation1 = Relu()
layer2 = DenseLayer(3,3)
activation2 = softmax()

#forward passing through layers and functions now
layer1.forward(X)
activation1.forward(layer1.output)
layer2.forward(activation1.output)
activation2.forward(layer2.output)

print("Probabilities of classes, columns=classes, rows=batch of data")
print(activation2.output[:5])
print("Sum of probabilities of all 3 classes")
print(np.sum(activation2.output,axis =1,keepdims=True)[:5])

Probabilities of classes, columns=classes, rows=batch of data
[[0.33333334 0.33333334 0.33333334]
 [0.33333308 0.33333337 0.33333355]
 [0.33333322 0.33333355 0.33333322]
 [0.33333248 0.33333322 0.33333427]
 [0.33333248 0.33333355 0.33333403]]
Sum of probabilities of all 3 classes
[[1.        ]
 [1.        ]
 [1.        ]
 [0.99999994]
 [1.        ]]
