In [20]:
# Cross entropy loss
# -summation(True_label*log(probability))

#Advanced indexing in python = matrix[[0,1,2],[0,1,1]]
#Selects the 0th index from row 0, 1st index from row 1, 1st index from row 2

In [21]:
import numpy as np

In [22]:
#as the cross entropy loss can only be calculated using the true label, the others don't matter
#we need to extract the probabilities of the required classes only

###When class targets are provided

In [30]:
#Suppose we got these probabilistic values as output from a 3 neuron final layer with 3 batches of data
softmax_outputs = np.array([[0.7, 0.1, 0.2],
 [0.1, 0.5, 0.4],
 [0.02, 0.9, 0.08]])
class_targets = np.array([0,1,1])
#Extracting the required softmax outputs using advanced indexing
print(softmax_outputs[[0,1,2],class_targets])

[0.7 0.5 0.9]


In [24]:
print(softmax_outputs[range(len(softmax_outputs)),class_targets]) #here this is equal to range(3) = 0,1,2, then it pairs up these with the class targets

[0.7 0.5 0.9]


In [25]:
#Now we can calculate losses easily
output_list=softmax_outputs[[0,1,2],class_targets]
loss = -np.log(output_list)
average_loss = np.mean(loss)
print(loss,average_loss)

[0.35667494 0.69314718 0.10536052] 0.38506088005216804


###When class targets are one-hot encoded

In [26]:
#Just multiply the class encoded matrix elementwise to the output matrix
y_true_check = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 1, 0]
])

y_pred_clipped_check = np.array([
    [0.7, 0.1, 0.2],
    [0.1, 0.5, 0.4],
    [0.02, 0.9, 0.08]
])

output_matrix = y_true_check*y_pred_clipped_check
prob_matrix= np.sum(output_matrix,axis =1)
print(prob_matrix)
loss_matrix = -np.log(prob_matrix)
print(loss_matrix)
print("Average loss: ",np.mean(loss_matrix))

[0.7 0.5 0.9]
[0.35667494 0.69314718 0.10536052]
Average loss:  0.38506088005216804


In [27]:
#Parent loss class, to calculate the loss per batch, and mean.
#the forward method will be in the child class, which will calculate the loss per batch
class Loss:
  def calculate(self,x,y):
    sample_losses = self.forward(x,y)
    return np.mean(sample_losses)

In [28]:
class Crossentropyloss(Loss):
  def forward(self,y_pred,y_target):
    samples = len(y_pred)
    y_pred_clipped = np.clip(y_pred,1e-7,1-1e-7)

    if len(y_target.shape)==1:
      required_confidences = y_pred_clipped[range(samples),y_target]
    elif len(y_target.shape)==2:
      required_confidences= np.sum(y_pred_clipped*y_target,axis=1)

    losses = -np.log(required_confidences)
    return losses

In [31]:
#applying these classes to our above softmax outputs and class target labels
loss_function = Crossentropyloss()
loss = loss_function.calculate(softmax_outputs,class_targets) #gets the final mean loss
print(loss)

0.38506088005216804


In [35]:
#accuracy
predictions = np.argmax(softmax_outputs,axis=1)
if(class_targets.shape)==2:
  class_targets = np.argmax(class_targets,axis=1)
accuracy = np.mean(predictions==class_targets)
print(accuracy)

1.0


In [ ]:
#Hence, our flow becomes
# Denselayer1->Relu->Denselayer2->Softmax->lossfunctionevaluation